use tempDB;
drop Database DoctorWho;
Create Database DoctorWho;
use  DoctorWho;
Create Table tblEnemy(EnemyId int,EnemyName varchar(32),EnemyDescription text,primary key (EnemyId));
Create Table tblAuthor(AuthorId int,AuthorName varchar(32),primary key (AuthorId));
Create Table tblDoctor(DoctorId int,DoctorNumber int,DoctorName varchar(32),BirthDate Date,FirstEpisodeDate Date,LastEpisodeDate Date,primary key (DoctorId));
Create Table tblCompanion(CompanionId int,CompanionName varchar(32),WhoPlayed varchar(32),primary key (CompanionId));
Create Table tblEpisode(EpisodeId int,SeriesNumber int,EpisodeNumber int,EpisodeType varchar(32),Title varchar(32),EpisodeDate Date,AuthorId int,primary key (EpisodeId),Foreign Key (AuthorId) references tblAuthor(AuthorId));
Create Table tblEpisodeEnemy(EpisodeEnemyId int,EpisodeId int,EnemyId int,primary key (EpisodeEnemyId), foreign key (EnemyId) references tblEnemy(EnemyId),foreign key (EpisodeId) references tblEpisode(EpisodeId));
Create Table tblEpisodeCompanion(EpisodeCompanionId int,EpisodeId int,CompanionId int,primary key (EpisodeCompanionId), foreign key (CompanionId) references tblCompanion(CompanionId),foreign key (EpisodeId) references tblEpisode(EpisodeId));